[workspace]
resolver = "2"
members = [
    "crates/shared",
    "crates/server",
    "crates/client",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Lost Connection <seth@lostconnection.dev>"]
