[application]
name = "forumall"
asset_dir = "assets"

[web.app]
title = "Forumall"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
